name: On Comment Test

on:
  issue_comment:
    types: [ created ]

jobs:
  pr_commented:
    name: PR comment
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, 'system-test') }}
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}: ${{ github.event.comment.body }}"
